#!/usr/bin/env python3
"""Parse disco_del_giorno.txt into structured albums.json.

The source list mixes two formats:
    "Album (year) - Artist"
    "Artist - Album (year)"

Key signal: the segment that carries the "(year)" is the ALBUM; the other
segment is the ARTIST. Where there is no year we fall back to "Artist - Album".
Run: python3 scripts/parse.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "disco_del_giorno.txt"
OUT = ROOT / "data" / "albums.json"

YEAR_RE = re.compile(r"\((\d{4})\)")

# A few entries are too irregular for the generic rules; pin them by hand.
OVERRIDES = {
    "Peter Gabriel III - Melt (1980) - Peter Gabriel": ("Peter Gabriel", "Peter Gabriel III (Melt)", 1980),
    "San Francisco’s Still Doomed - 1976/78 (1990) - Crime": ("Crime", "San Francisco’s Still Doomed (1976/78)", 1990),
    "DNA on DNA (1977-1981) (2004) - DNA": ("DNA", "DNA on DNA (1977-1981)", 2004),
    "Disco del giorno Sign O' the Times (1987) - Prince": ("Prince", "Sign O' the Times", 1987),
    "Disco del giorno: 77 (1977) - Talking Heads": ("Talking Heads", "77", 1977),
    "T. Rex - Electric Warrior": ("T. Rex", "Electric Warrior", None),
}


def extract_year(text):
    """Return the release year: the last plain 4-digit (year) group."""
    years = YEAR_RE.findall(text)
    return int(years[-1]) if years else None


def strip_year(text):
    """Remove year parens, collapse whitespace."""
    return re.sub(r"\s*\(\d{4}\)\s*", " ", text).strip()


def parse_line(raw):
    line = raw.strip()
    if not line:
        return None
    if line in OVERRIDES:
        artist, album, year = OVERRIDES[line]
        return {"artist": artist, "album": album, "year": year}

    line = re.sub(r"^Disco del giorno:?\s*", "", line)
    # normalise hyphen separators with a missing space on one side:
    # "(1993) -Earth" (no trailing space) and "(1989)- Numb" (no leading space).
    # A real separator has a space on at least one side; hyphenated names
    # (e.g. Sleater-Kinney) have none, so they stay intact.
    line = re.sub(r"\s+-\s*", " - ", line)
    line = re.sub(r"(?<=\S)-\s+", " - ", line)

    year = extract_year(line)
    segments = [s.strip() for s in line.split(" - ")]

    if len(segments) == 1:
        # no separator: assume the whole thing is the album, artist unknown
        return {"artist": "", "album": strip_year(segments[0]), "year": year}

    if year is None:
        # no year signal -> assume "Artist - Album"
        artist = segments[0]
        album = " - ".join(segments[1:])
        return {"artist": artist, "album": album, "year": None}

    # year present: the segment holding it is the album
    year_idx = next((i for i, s in enumerate(segments) if YEAR_RE.search(s)), 0)
    if year_idx == 0:
        album = strip_year(" - ".join(segments[:-1])) if len(segments) > 2 else strip_year(segments[0])
        artist = segments[-1]
    else:
        artist = segments[0]
        album = strip_year(" - ".join(segments[1:]))
    return {"artist": artist.strip(), "album": album.strip(), "year": year}


def slugify(*parts):
    s = " ".join(str(p) for p in parts if p)
    s = s.lower().translate(str.maketrans("àáäâãèéëêìíïîòóöôõùúüûñç", "aaaaaeeeeiiiiooooouuuunc"))
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s or "disco"


def main():
    albums = []
    for raw in SRC.read_text(encoding="utf-8").splitlines():
        rec = parse_line(raw)
        if rec and rec["album"]:
            albums.append(rec)

    albums.sort(key=lambda r: (r["artist"].lower(), r["year"] or 0))

    # stable id per album (used to attach cover art across re-runs)
    seen = {}
    for rec in albums:
        base = slugify(rec["artist"], rec["album"], rec["year"])
        n = seen.get(base, 0)
        seen[base] = n + 1
        rec["id"] = base if n == 0 else base + "-" + str(n + 1)
    payload = json.dumps(albums, ensure_ascii=False, indent=1)
    OUT.write_text(payload, encoding="utf-8")
    # Also emit a plain-JS wrapper so the site opens straight from file://
    # without tripping CORS on fetch().
    (OUT.parent / "albums.js").write_text(
        "// Generated by scripts/parse.py — do not edit by hand.\n"
        f"window.ALBUMS = {payload};\n",
        encoding="utf-8",
    )

    no_year = [a for a in albums if a["year"] is None]
    no_artist = [a for a in albums if not a["artist"]]
    print(f"parsed {len(albums)} albums -> {OUT.relative_to(ROOT)}")
    print(f"no year: {len(no_year)} | no artist: {len(no_artist)}")
    for a in no_year:
        print("  NO YEAR:", a)
    for a in no_artist:
        print("  NO ARTIST:", a)


if __name__ == "__main__":
    sys.exit(main())
